---
- name: test if go_version is set correctly
  assert:
    that:
      - go_version is defined
      - go_version | length > 0

- name: test if go_destination is set correctly
  assert:
    that:
      - go_destination is defined
      - go_destination | length > 0

- name: test if go_path is set correctly
  assert:
    that:
      - go_path is defined
      - go_path | length > 0
