---

- name: test if go_version is set correctly
  assert:
    that:
      - go_version is defined
    quiet: yes

- name: test if go_destination is set correctly
  assert:
    that:
      - go_destination is defined
    quiet: yes

- name: test if go_path is set correctly
  assert:
    that:
      - go_path is defined
    quiet: yes
