---
# tasks file for go
- name: unpack go
  unarchive:
    src: "{{ go_src }}"
    dest: "{{ go_destination }}"
    remote_src: yes
    creates: "{{ go_destination }}/go/bin"
  register: go_unpack_go
  until: go_unpack_go is succeeded
  retries: 3

- name: add go_destination to path variable
  template:
    src: go.sh.j2
    dest: /etc/profile.d/{{ item }}
    mode: '0644'
  with_items:
    - go.sh
    - go.csh

- name: link go to a location in PATH
  file:
    src: "{{ go_destination }}/go/bin/go"
    dest: /usr/bin/go
    state: link

- name: get requested packages
  command: go get {{ item }}
  args:
    creates: "{{ go_path }}/go/src/{{ item }}"
  with_items:
    - "{{ go_packages | default([]) }}"
  environment:
    GOPATH: "{{ go_path }}"

- name: create go_path bin directory
  file:
    path: "{{ go_path }}/go/bin"
    state: directory
  when:
    - go_packages is defined

- name: install requested packages
  command: make install
  args:
    chdir: "{{ go_path }}/go/src/{{ item }}"
    creates: "{{ go_path }}/go/bin/{{ item | basename }}"
  with_items:
    - "{{ go_packages | default([]) }}"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ go_destination }}/go/bin"
