---
# tasks file for go
- name: unpack go
  unarchive:
    src: "{{ go_src }}"
    dest: "{{ go_destination }}"
    remote_src: yes
    creates: "{{ go_destination }}/go/bin/go"
  register: go_unpack_go
  until: go_unpack_go is succeeded
  retries: 3

- name: add go to path variable
  template:
    src: go.sh.j2
    dest: /etc/profile.d/go.sh
    mode: '0755'

- name: go get packages
  command: go get {{ item }}
  args:
    creates: "{{ go_root }}/go/src/{{ item }}"
  with_items:
    - "{{ go_packages | default([]) }}"
  environment:
    GOROOT: "{{ go_root }}"

- name: make install
  command: make install
  args:
    chdir: "{{ go_root }}/go/src/{{ item }}"
    creates: "{{ go_root }}/go/bin/{{ item | basename }}"
  with_items:
    - "{{ go_packages | default([]) }}"
