---
# tasks file for go
- name: unpack go in /usr/local/go
  unarchive:
    src: "{{ go_src }}"
    dest: "{{ go_destination }}"
    remote_src: yes

- name: add go to path variable
  template:
    src: go.sh.j2
    dest: /etc/profile.d/go.sh
