---
- name: Converge
  hosts: all
  gather_facts: false
  become: true

  vars:
    go_packages:
      - github.com/golang/dep

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.buildtools
    - role: robertdebock.git
    - role: ansible-role-go
